# Generated by Django 2.2.2 on 2019-06-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('end_date', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('house', 'household'), ('proj', 'project'), ('save', 'saving'), ('sp', 'special')], default='household', max_length=50)),
            ],
        ),
    ]
